# Site settings
title: Pinecode
email: steve@pinecode.ca

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0082FF
  secondary: 0A1E23
  secondary-dark: 2B303B

# Social network usernames
social:
  - title: twitter
    url: http://twitter.com/pinecodedotca
  - title: github
    url: http://github.com/pinecode

# Postal address
address:
  - line: 1050 Southgate St.
  - line: Victoria, BC
  - line: V8V 2Z2

# Build settings
markdown: kramdown
permalink: pretty
